version: "3.7"
services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    # Enable pg_stat_statements.
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - $DB_HOST:$DB_PORT:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 127.0.0.1:6379:6379
