// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/alextanhongpin/go-graphql-template/domain"
	"github.com/alextanhongpin/go-graphql-template/domain/account"
	"github.com/alextanhongpin/go-graphql-template/domain/entity"
	"github.com/alextanhongpin/go-graphql-template/domain/user"
	"github.com/alextanhongpin/go-graphql-template/external"
	"github.com/alextanhongpin/go-graphql-template/external/security"
	"github.com/alextanhongpin/go-graphql-template/internal"
	"net/http"
)

// Injectors from wire.go:

func New() (http.Handler, func()) {
	db, cleanup := internal.NewDB()
	queries := entity.New(db)
	jwtConfig := security.NewAuthorizerConfig()
	jwtAuthorizer := security.NewAuthorizer(jwtConfig)
	repository := domain.NewRepository(queries)
	userRepository := repository.User
	jsonValidator := internal.NewValidator()
	userService := user.NewService(userRepository, jsonValidator)
	accountRepository := repository.Account
	accountService := account.NewService(accountRepository, jsonValidator)
	handler := external.NewGraph(queries, jwtAuthorizer, userService, accountService)
	return handler, func() {
		cleanup()
	}
}
